version: '3'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app:rw
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - 8001:8001
    volumes:
      - ./src:/app:rw
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ESKIZ_BASE_URL=${ESKIZ_BASE_URL}
      - ESKIZ_EMAIL=${ESKIZ_EMAIL}
      - ESKIZ_PASSWORD=${ESKIZ_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - db
    
  
  celery:
    build: .
    command: celery -A celery worker
    volumes:
      - ./src:/app:rw
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - django
      - redis
  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: