# Generated by Django 5.2 on 2025-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_role_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PREMIUM', 'PREMIUM')], default='FREE', max_length=10),
        ),
    ]
